### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by ferdw** [TedTolboom/hk.com.remotec#8] opened 2018-02-12 19:16 UTC
on the Homey Firmware Versie: 1.5.6-rc.13 firmware the app crashes immediately when pushing a button on the Remotec Scene (8 button remote)

**Comment by TedTolboom** [comment] 2018-02-14 09:08
@ferdw thanks for reporting.
I did receive a crashlog, but it was empty; so no info to check what the cause of the issue is...

Can you reproduce the crash and send me the crashlog as shown in:
my.athom.com > Settings > Apps > hoovering over the red triangle next to the Remotec app name will show you the crashlog

**Comment by TedTolboom** [comment] 2018-02-23 19:35
@ferdw thanks for reporting!
The issue is originating in that in 1.5.6 Athom removed some private properties, like `__state` which I used for the battery_alarm condition card.

So you can prevent the app from crashing when disabling (or removing) the battery alarm condition card.

In the meantime, Athom has implemented the battery alarm capability (incl. flow cards) as standard capability... so solution would be to remove the original (custom) condition card out of the Remotec app... In order to be able to use the default condition card, the device will need to be re-included (and flows repaired).

BUT, I've prepared the app update and tested the re-inclusion of the Remotec Scene Master on 1.5.6 and bumped into a new issue in 1.5.6 where the device no longer reports the key presses towards Homey. Athom is currently looking into this issue, see https://github.com/athombv/homey/issues/2258

So advice for now is to disable (or remove) the condition card and wait for the fix of this issue

**Comment by TedTolboom** [comment] 2018-03-18 21:42
@ferdw should be fixed now in the latest app store version; can you confirm?

**Comment by TedTolboom** [comment] 2018-05-06 18:56
@ferdw I will close the issue; assume that it has been resolved. 
If not, please let me know and I'll open it again

**Closed by TedTolboom** 2018-05-06 18:56 UTC
